apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: otelcollector
      context: deploy/config-files/custom-collector
      docker:
        dockerfile: deploy/config-files/custom-collector/Dockerfile
    - image: accounting
      context: .
      docker:
        dockerfile: src/accounting/Dockerfile
    - image: ad
      context: .
      docker:
        dockerfile: src/ad/Dockerfile
        buildArgs:
          OTEL_JAVA_AGENT_VERSION: 2.21.0
    - image: cart
      context: .
      docker:
        dockerfile: src/cart/src/Dockerfile
    - image: checkout
      context: .
      docker:
        dockerfile: src/checkout/Dockerfile
    - image: currency
      context: .
      docker:
        dockerfile: src/currency/Dockerfile
        buildArgs:
          OPENTELEMETRY_CPP_VERSION: 1.23.0
    - image: email
      context: .
      docker:
        dockerfile: src/email/Dockerfile
    - image: fraud-detection
      context: .
      docker:
        dockerfile: src/fraud-detection/Dockerfile
        buildArgs:
          OTEL_JAVA_AGENT_VERSION: 2.21.0
    - image: frontend
      context: .
      docker:
        dockerfile: src/frontend/Dockerfile
      hooks:
        after:
          - command:
              - "./scripts/extract-and-upload-js-sourcemaps-s3.sh"
              - "--repo"
              - "$SKAFFOLD_IMAGE_REPO"
              - "--container-path"
              - "/app/.next/static/"
              - "--version"
              - "$SKAFFOLD_IMAGE_TAG"
              - "--prefix"
              - "$SOURCE_MAPS_PREFIX"
    - image: frontendproxy
      context: .
      docker:
        dockerfile: src/frontend-proxy/Dockerfile
    - image: image-provider
      context: .
      docker:
        dockerfile: src/image-provider/Dockerfile
    - image: kafka
      context: .
      docker:
        dockerfile: src/kafka/Dockerfile
        buildArgs:
          OTEL_JAVA_AGENT_VERSION: 2.21.0
    - image: llm
      context: .
      docker:
        dockerfile: src/llm/Dockerfile
    - image: load-generator
      context: .
      docker:
        dockerfile: src/load-generator/Dockerfile
    - image: payment
      context: .
      docker:
        dockerfile: src/payment/Dockerfile
    - image: postgresql
      context: .
      docker:
        dockerfile: src/postgres/Dockerfile
    - image: product-catalog
      context: .
      docker:
        dockerfile: src/product-catalog/Dockerfile
    - image: product-reviews
      context: .
      docker:
        dockerfile: src/product-reviews/Dockerfile
    - image: quote
      context: .
      docker:
        dockerfile: src/quote/Dockerfile
    - image: recommendation
      context: .
      docker:
        dockerfile: src/recommendation/Dockerfile
    - image: shipping
      context: .
      docker:
        dockerfile: src/shipping/Dockerfile
  platforms:
    - linux/amd64
  local:
    useDockerCLI: true
portForward:
  - resourceType: service
    resourceName: "frontend-proxy"
    namespace: "{{.USER}}-local"
    port: 8080
    localPort: 9191
deploy:
  helm:
    releases:
      - name: "{{.USER}}"
        createNamespace: true
        namespace: "{{.USER}}-local"
        repo: https://open-telemetry.github.io/opentelemetry-helm-charts
        remoteChart: opentelemetry-demo
        version: 0.39.0
        recreatePods: false
        skipBuildDependencies: false
        valuesFiles:
          - deploy/config-files/demo/values.yaml
          - skaffold-config/demo-values.yaml
        setValues:
          default:
            image:
              pullPolicy: Always
          opentelemetry-collector:
            extraEnvs:
              - name: HONEYCOMB_API_KEY
              - name: HTP_ENDPOINT
              - name: CLOUD_PROVIDER
              - name: SOURCE_MAPS_BUCKET
              - name: AWS_REGION
              - name: SOURCE_MAPS_PREFIX
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
        setValueTemplates:
          opentelemetry-collector.extraEnvs[0].value: "{{.HONEYCOMB_API_KEY}}"
          opentelemetry-collector.extraEnvs[1].value: "{{.USER}}-htp-htp-builder-primary-collector:4317"
          opentelemetry-collector.extraEnvs[2].value: "{{.CLOUD_PROVIDER}}"
          opentelemetry-collector.extraEnvs[3].value: "{{.SOURCE_MAPS_BUCKET}}"
          opentelemetry-collector.extraEnvs[4].value: "{{.SOURCE_MAPS_BUCKET_REGION}}"
          opentelemetry-collector.extraEnvs[5].value: "{{if .IMAGE_REPO_frontend}}{{.SOURCE_MAPS_PREFIX}}/static/chunks{{else}}source-maps/static/chunks{{end}}"
          opentelemetry-collector.clusterRole.name: "{{.USER}}-otel-collector"
          opentelemetry-collector.clusterRole.clusterRoleBinding.name: "{{.USER}}-otel-collector"
          opentelemetry-collector.image.repository: "{{if .IMAGE_REPO_otelcollector }}{{.IMAGE_REPO_otelcollector}}{{else}}ghcr.io/honeycombio/devrel-opentelemetry-demo{{end}}"
          opentelemetry-collector.image.tag: "{{if .IMAGE_REPO_otelcollector }}{{.IMAGE_TAG_otelcollector}}@{{.IMAGE_DIGEST_otelcollector}}{{else}}latest-collector{{end}}"
          components.accounting.imageOverride.repository: "{{if .IMAGE_REPO_accounting }}{{.IMAGE_REPO_accounting}}{{end}}"
          components.accounting.imageOverride.tag: "{{if .IMAGE_REPO_accounting }}{{.IMAGE_TAG_accounting}}@{{.IMAGE_DIGEST_accounting}}{{end}}"
          components.ad.imageOverride.repository: "{{if .IMAGE_REPO_ad }}{{.IMAGE_REPO_ad}}{{end}}"
          components.ad.imageOverride.tag: "{{if .IMAGE_REPO_ad }}{{.IMAGE_TAG_ad}}@{{.IMAGE_DIGEST_ad}}{{end}}"
          components.cart.imageOverride.repository: "{{if .IMAGE_REPO_cart }}{{.IMAGE_REPO_cart}}{{end}}"
          components.cart.imageOverride.tag: "{{if .IMAGE_REPO_cart }}{{.IMAGE_TAG_cart}}@{{.IMAGE_DIGEST_cart}}{{end}}"
          components.checkout.imageOverride.repository: "{{if .IMAGE_REPO_checkout }}{{.IMAGE_REPO_checkout}}{{end}}"
          components.checkout.imageOverride.tag: "{{if .IMAGE_REPO_checkout }}{{.IMAGE_TAG_checkout}}@{{.IMAGE_DIGEST_checkout}}{{end}}"
          components.currency.imageOverride.repository: "{{if .IMAGE_REPO_currency }}{{.IMAGE_REPO_currency}}{{end}}"
          components.currency.imageOverride.tag: "{{if .IMAGE_REPO_currency }}{{.IMAGE_TAG_currency}}@{{.IMAGE_DIGEST_currency}}{{end}}"
          components.email.imageOverride.repository: "{{if .IMAGE_REPO_email }}{{.IMAGE_REPO_email}}{{end}}"
          components.email.imageOverride.tag: "{{if .IMAGE_REPO_email }}{{.IMAGE_TAG_email}}@{{.IMAGE_DIGEST_email}}{{end}}"
          components.fraud-detection.imageOverride.repository: "{{if .IMAGE_REPO_fraud_detection }}{{.IMAGE_REPO_fraud_detection}}{{end}}"
          components.fraud-detection.imageOverride.tag: "{{if .IMAGE_REPO_fraud_detection }}{{.IMAGE_TAG_fraud_detection}}@{{.IMAGE_DIGEST_fraud_detection}}{{end}}"
          components.frontend.imageOverride.repository: "{{if .IMAGE_REPO_frontend }}{{.IMAGE_REPO_frontend}}{{end}}"
          components.frontend.imageOverride.tag: "{{if .IMAGE_REPO_frontend }}{{.IMAGE_TAG_frontend}}@{{.IMAGE_DIGEST_frontend}}{{end}}"
          components.frontend-proxy.imageOverride.repository: "{{if .IMAGE_REPO_frontendproxy }}{{.IMAGE_REPO_frontendproxy}}{{end}}"
          components.frontend-proxy.imageOverride.tag: "{{if .IMAGE_REPO_frontendproxy }}{{.IMAGE_TAG_frontendproxy}}@{{.IMAGE_DIGEST_frontendproxy}}{{end}}"
          components.image-provider.imageOverride.repository: "{{if .IMAGE_REPO_image_provider }}{{.IMAGE_REPO_image_provider}}{{end}}"
          components.image-provider.imageOverride.tag: "{{if .IMAGE_REPO_image_provider }}{{.IMAGE_TAG_image_provider}}@{{.IMAGE_DIGEST_image_provider}}{{end}}"
          components.kafka.imageOverride.repository: "{{if .IMAGE_REPO_kafka }}{{.IMAGE_REPO_kafka}}{{end}}"
          components.kafka.imageOverride.tag: "{{if .IMAGE_REPO_kafka }}{{.IMAGE_TAG_kafka}}@{{.IMAGE_DIGEST_kafka}}{{end}}"
          components.load-generator.imageOverride.repository: "{{if .IMAGE_REPO_load_generator }}{{.IMAGE_REPO_load_generator}}{{end}}"
          components.load-generator.imageOverride.tag: "{{if .IMAGE_REPO_load_generator }}{{.IMAGE_TAG_load_generator}}@{{.IMAGE_DIGEST_load_generator}}{{end}}"
          components.payment.imageOverride.repository: "{{if .IMAGE_REPO_payment }}{{.IMAGE_REPO_payment}}{{end}}"
          components.payment.imageOverride.tag: "{{if .IMAGE_REPO_payment }}{{.IMAGE_TAG_payment}}@{{.IMAGE_DIGEST_payment}}{{end}}"
          components.postgresql.imageOverride.repository: "{{if .IMAGE_REPO_postgresql }}{{.IMAGE_REPO_postgresql}}{{end}}"
          components.postgresql.imageOverride.tag: "{{if .IMAGE_REPO_postgresql }}{{.IMAGE_TAG_postgresql}}@{{.IMAGE_DIGEST_postgresql}}{{end}}"
          components.product-catalog.imageOverride.repository: "{{if .IMAGE_REPO_product_catalog }}{{.IMAGE_REPO_product_catalog}}{{end}}"
          components.product-catalog.imageOverride.tag: "{{if .IMAGE_REPO_product_catalog }}{{.IMAGE_TAG_product_catalog}}@{{.IMAGE_DIGEST_product_catalog}}{{end}}"
          components.quote.imageOverride.repository: "{{if .IMAGE_REPO_quote }}{{.IMAGE_REPO_quote}}{{end}}"
          components.quote.imageOverride.tag: "{{if .IMAGE_REPO_quote }}{{.IMAGE_TAG_quote}}@{{.IMAGE_DIGEST_quote}}{{end}}"
          components.recommendation.imageOverride.repository: "{{if .IMAGE_REPO_recommendation }}{{.IMAGE_REPO_recommendation}}{{end}}"
          components.recommendation.imageOverride.tag: "{{if .IMAGE_REPO_recommendation }}{{.IMAGE_TAG_recommendation}}@{{.IMAGE_DIGEST_recommendation}}{{end}}"
          components.shipping.imageOverride.repository: "{{if .IMAGE_REPO_shipping }}{{.IMAGE_REPO_shipping}}{{end}}"
          components.shipping.imageOverride.tag: "{{if .IMAGE_REPO_shipping }}{{.IMAGE_TAG_shipping}}@{{.IMAGE_DIGEST_shipping}}{{end}}"
        upgradeOnChange: true
        useHelmSecrets: false
        wait: true
      - name: "{{.USER}}-otel-services"
        createNamespace: true
        namespace: "{{.USER}}-local"
        chartPath: skaffold-config/charts/otel-services
        recreatePods: false
        skipBuildDependencies: false
        setValueTemplates:
          services.productReviews.imageOverride.repository: "{{if .IMAGE_REPO_product_reviews }}{{.IMAGE_REPO_product_reviews}}{{end}}"
          services.productReviews.imageOverride.tag: "{{if .IMAGE_REPO_product_reviews }}{{.IMAGE_TAG_product_reviews}}@{{.IMAGE_DIGEST_product_reviews}}{{end}}"
          services.llm.imageOverride.repository: "{{if .IMAGE_REPO_llm }}{{.IMAGE_REPO_llm}}{{end}}"
          services.llm.imageOverride.tag: "{{if .IMAGE_REPO_llm }}{{.IMAGE_TAG_llm}}@{{.IMAGE_DIGEST_llm}}{{end}}"
          ingress.domainName: "{{if .DOMAINNAME}}{{.DOMAINNAME}}{{else}}aurelia.honeydemo.io{{end}}"
          ingress.subDomainName: "{{.USER}}-local"
          ingress.enabled: true
          ingress.className: "{{if .INGRESS_CLASS}}{{.INGRESS_CLASS}}{{else}}alb{{end}}"
          ingress.generateCertificate: '{{if eq .CLOUD_PROVIDER "aws"}}false{{else}}true{{end}}'
        upgradeOnChange: true
        useHelmSecrets: false
        wait: true
      - name: "{{.USER}}-htp"
        createNamespace: true
        namespace: "{{.USER}}-local"
        repo: https://honeycombio.github.io/helm-charts
        remoteChart: htp-builder
        version: 0.2.0
        recreatePods: false
        skipBuildDependencies: false
        setValueTemplates:
          pipeline.id: "{{.PIPELINE_ID}}"
          managementApiKey.id: "{{.PIPELINE_MANAGEMENT_API_KEY_ID}}"
        upgradeOnChange: true
        useHelmSecrets: false
        wait: true
    hooks:
      after:
        - host:
            command:
              - "./scripts/setup-pod-identity-association.sh"
              - "--namespace"
              - "$USER-local"
