on:
  workflow_call:
    inputs:
      push:
        description: Should the images be pushed
        default: false
        required: false
        type: boolean
      version:
        description: The version used when tagging the image
        default: 'dev'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      push:
        description: Should the images be pushed
        default: false
        required: false
        type: boolean
      version:
        description: The version used when tagging the image
        default: 'dev'
        required: false
        type: string


jobs:
  build_custom_collector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Docker metadata
        id: docker_metatdata
        uses: docker/metadata-action@v3
        with:
          images: |
            name=ghcr.io/${{ github.repository }}
          tags: | 
            type=raw,value=${{ inputs.version }}
            type=raw,value=latest

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ inputs.push }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
            max-parallelism = 2

      - name: Build and push custom collector image
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./deploy/config-files/custom-collector
          file: ./deploy/config-files/custom-collector/Dockerfile
          platforms: linux/amd64 # ,linux/arm64
          push: ${{ inputs.push }}
          tags: ${{ steps.docker_metatdata.outputs.tags }}
          labels: ${{ steps.docker_metatdata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
