# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "[DevRel] Deploy Latest"

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: pulumi/actions@v6
      - uses: pulumi/auth-actions@v1
        with:
          organization: ${{ secrets.PULUMI_ORG }}
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:${{ github.actor }}
          token-expiration: 600
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: |
          pulumi stack select --stack ${{ secrets.PULUMI_ORG }}/prod --non-interactive
          pulumi config refresh --non-interactive
        working-directory: deploy

      - run: |
          npm ci
        working-directory: deploy

      - id: pulumi-deploy
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_ORG }}/prod
          work-dir: deploy
          config-map: |
            devrel-opentelemetry-demo:container-tag: 
              value: latest
              secret: false
            devrel-opentelemetry-demo:collector-container-tag: 
              value: latest-co1lector
              secret: false
            devrel-opentelemetry-demo:collector-container-repository: 
              value: ghcr.io/${{ github.repository }}
              secret: false
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
          IS_IN_PIPELINE: true

      - name: Extract and upload js sourcemaps
        run: ./scripts/extract-and-upload-js-sourcemaps.sh
        env:
          REPO: ghcr.io/${{ github.repository }}
          CONTAINER_PATH: /app/.next/static/js
          BLOB_CONTAINER_NAME: ${{ steps.pulumi-deploy.outputs.blobContainerName }}
          STORAGE_ACCOUNT_NAME: ${{ steps.pulumi-deploy.outputs.storageAccountName }}
          VERSION: latest
