# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "[DevRel] Deploy Latest"

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: pulumi/auth-actions@v1
        with:
          organization: ${{ secrets.PULUMI_ORG }}
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: team:${{ github.actor }}

      # run a pulumi stack select and config refresh
      - run: |
          pulumi config refresh --stack ${{ secrets.PULUMI_ORG }}/prod

      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_ORG }}/prod
          work-dir: deploy
          config-map: |
            devrel-opentelemetry-demo:container-tag: latest
