# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "[DevRel] Deploy Latest"

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: pulumi/actions@v6
      - uses: pulumi/auth-actions@v1
        with:
          organization: ${{ secrets.PULUMI_ORG }}
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:${{ github.actor }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: |
          pulumi config refresh --stack ${{ secrets.PULUMI_ORG }}/prod
        working-directory: ./deploy

      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_ORG }}/prod
          work-dir: deploy
          config-map: |
            devrel-opentelemetry-demo:container-tag: latest
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
